// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
// import { env } from './.env';

export const environment = {
  production: true,
  // apiUrl: 'https://localhost:7118',
  // apiUrl: 'http://192.168.5.107:82',
  apiUrl: `http://${window.location.hostname}:82`,
  version: '1', // env.npm_package_version + '-dev',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.

export class EnvService {
  // The values that are defined here are the default values that can
  // be overridden by env.js

  // API url
  // public apiUrl = 'http://192.168.5.107:82';
  public apiUrl = 'http://192.168.1.138/MemWebApi';
  // public   apiUrl= 'https://localhost:7118';
  public reportUrl = '';
  public secrectKey = '';

  // Whether or not to enable debug mode
  public enableDebug = true;

  constructor() {}
}
